[workspace]

members = [
    "remainder_prover",
    "remainder_shared_types",
    "remainder_ligero",
    "remainder_hyrax",
    "remainder_zkdt",
]

resolver = "2"

[profile.release-with-debug]
inherits = "release"
debug = true
